overrides:
  nanoid: ^3.3.18
  svgo@>=4.0.0 <4.1.0: '>=4.1.0'
  js-yaml@>=4.0.0 <4.3.2: '>=4.3.2'
  devalue@<5.9.1: ^5.9.1
  undici@>=8.0.0 <8.10.2: ^8.10.2

allowBuilds:
  '@jasikpark/astro-svg-loader': true
  esbuild: true
  sharp: true
  wrangler: true
  workerd: true
onlyBuiltDependencies:
  - '@jasikpark/astro-svg-loader'
  - esbuild
  - sharp
  - workerd
